/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        "background": "#fbf8fe",
        "surface": "#fbf8fe",
        "surface-dim": "#dbd9e3",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f2fa",
        "surface-container": "#efedf5",
        "surface-container-high": "#e9e7f0",
        "surface-container-highest": "#e3e1ec",
        "surface-variant": "#e3e1ec",
        "on-background": "#31323a",
        "on-surface": "#31323a",
        "on-surface-variant": "#5e5e67",
        "primary": "#4f4dcf",
        "primary-container": "#7777fa",
        "primary-dim": "#423fc2",
        "on-primary": "#fbf7ff",
        "on-primary-container": "#000000",
        "secondary": "#5c5c7c",
        "secondary-container": "#e1dfff",
        "on-secondary": "#fbf7ff",
        "on-secondary-container": "#4f4f6e",
        "tertiary": "#755478",
        "tertiary-container": "#fcd2fe",
        "on-tertiary": "#fff7fa",
        "on-tertiary-container": "#654569",
        "error": "#a8364b",
        "error-container": "#f97386",
        "on-error": "#fff7f7",
        "on-error-container": "#6e0523",
        "outline": "#7a7a83",
        "outline-variant": "#b2b1bb",
        "inverse-primary": "#8282ff",
        "surface-tint": "#4f4dcf",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
      },
      borderRadius: {
        "xl": "1.25rem",
      },
    },
  },
  plugins: [],
};
