/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // All names resolve to the semantic CSS vars in src/index.css.
        // Light values reproduce production exactly (text neutrals corrected
        // to brand per 2026-05-29); dark comes from [data-theme="dark"].
        "background": "var(--surface)",
        "surface": "var(--surface)",
        "surface-dim": "var(--surface-dim)",
        "surface-container-lowest": "var(--surface-elevated)",
        "surface-container-low": "var(--surface-container-low)",
        "surface-container": "var(--surface-container)",
        "surface-container-high": "var(--surface-container-high)",
        "surface-container-highest": "var(--surface-container-highest)",
        "surface-variant": "var(--surface-variant)",
        "on-background": "var(--text-primary)",
        "on-surface": "var(--text-primary)",
        "on-surface-variant": "var(--text-secondary)",
        "primary": "var(--accent)",
        "primary-container": "var(--primary-container)",
        "primary-dim": "var(--primary-dim)",
        "on-primary": "var(--accent-contrast)",
        "on-primary-container": "var(--text-primary)",
        "secondary": "var(--secondary)",
        "secondary-container": "var(--secondary-container)",
        "on-secondary": "var(--accent-contrast)",
        "on-secondary-container": "var(--on-secondary-container)",
        "tertiary": "var(--tertiary)",
        "tertiary-container": "var(--tertiary-container)",
        "on-tertiary": "var(--accent-contrast)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "error": "var(--error)",
        "error-container": "var(--error-container)",
        "on-error": "var(--accent-contrast)",
        "on-error-container": "var(--on-error-container)",
        "outline": "var(--outline)",
        "outline-variant": "var(--outline-variant)",
        "inverse-primary": "var(--inverse-primary)",
        "surface-tint": "var(--accent)",
        // semantic helpers for direct class usage (text-success, bg-danger…)
        "accent": "var(--accent)",
        "accent-deep": "var(--accent-deep)",
        "accent-contrast": "var(--accent-contrast)",
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-faint": "var(--text-faint)",
        "success": "var(--success)",
        "danger": "var(--danger)",
        "warning": "var(--warning)",
        "glow": "var(--glow)",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
      },
      borderRadius: {
        "xl": "1.25rem",
      },
    },
  },
  plugins: [],
};
