import { useState, useEffect, useRef } from 'react';

/**
 * ActiveZoneVoice — empty-state panel.
 *
 * When the orchestrator has zero candidates, this panel shows ONE Aria
 * line (recap, light observation, or playful note). Generated by Haiku
 * on the backend, cached 30 min per user there. Locally we re-fetch
 * every 30 min as a guardrail in case the user keeps the dashboard
 * open without state changes.
 *
 * Subtle bordered block. Aria attribution. No actions — this is voice,
 * not a tile.
 */
export default function ActiveZoneVoice({ apiFetch, authToken, refreshKey }) {
  const [line, setLine] = useState('');
  const [loading, setLoading] = useState(false);
  const lastFetchRef = useRef(0);

  useEffect(() => {
    let cancelled = false;
    async function load() {
      // Local 30-min cooldown mirrors the server cache TTL — no point
      // hammering the route every refreshKey bump if the cache hasn't
      // rolled. The backend caches per (user × 30-min bucket) so any
      // call within the bucket returns the same line.
      if (Date.now() - lastFetchRef.current < 30 * 60 * 1000 && line) return;
      setLoading(true);
      try {
        const r = await apiFetch('/api/active-zone/voice', {
          headers: { Authorization: `Bearer ${authToken}` },
        });
        const data = await r.json().catch(() => ({}));
        if (!cancelled && data?.line) {
          setLine(data.line);
          lastFetchRef.current = Date.now();
        }
      } catch {
        if (!cancelled) setLine("You're all clear.");
      } finally {
        if (!cancelled) setLoading(false);
      }
    }
    load();
    return () => { cancelled = true; };
  }, [apiFetch, authToken, refreshKey, line]);

  // Diagnostic — surfaces in DevTools so we can confirm the panel
  // mounted and the API roundtrip succeeded. Cheap; remove later if
  // it gets noisy.
  if (typeof window !== 'undefined' && !window.__activeZoneVoiceLogged) {
    window.__activeZoneVoiceLogged = true;
    console.log('[ActiveZoneVoice] mounted');
  }

  return (
    <div
      className="rounded-2xl border-2 border-primary/15 bg-surface-container-lowest px-4 py-3 shadow-sm"
      style={{ animation: 'azSlideIn 200ms ease-out' }}
    >
      <div className="flex items-start gap-2.5">
        <span className="material-symbols-outlined text-primary flex-shrink-0 mt-0.5" style={{ fontSize: '18px' }}>auto_awesome</span>
        <div className="flex-1 min-w-0">
          <p className="text-[10px] font-extrabold uppercase tracking-wider text-primary mb-1">Aria</p>
          {loading && !line ? (
            <p className="text-sm text-on-surface-variant italic">Catching up…</p>
          ) : (
            <p className="text-sm text-on-background leading-relaxed">{line || "You're all clear. Nice work."}</p>
          )}
        </div>
      </div>
    </div>
  );
}
